// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlofy0uIK0VfMKLDzNORqLg7QolDwSF8',
    appId: '1:26711865738:android:822a7edf96560f9659f073',
    messagingSenderId: '26711865738',
    projectId: 'todoflutter-46f27',
    databaseURL: 'https://todoflutter-46f27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todoflutter-46f27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Z8a44yG6CmlORfFxWg5njiR7YEaRIRE',
    appId: '1:26711865738:ios:c2de0140939bb78c59f073',
    messagingSenderId: '26711865738',
    projectId: 'todoflutter-46f27',
    databaseURL: 'https://todoflutter-46f27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todoflutter-46f27.appspot.com',
    iosBundleId: 'com.iustinov.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Z8a44yG6CmlORfFxWg5njiR7YEaRIRE',
    appId: '1:26711865738:ios:c2de0140939bb78c59f073',
    messagingSenderId: '26711865738',
    projectId: 'todoflutter-46f27',
    databaseURL: 'https://todoflutter-46f27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todoflutter-46f27.appspot.com',
    iosBundleId: 'com.iustinov.flutterTodo',
  );
}
